export enum NotificationType {
  INQUIRY_QUOTED = 'INQUIRY_QUOTED',
  INQUIRY_FIELD_CHANGED = 'INQUIRY_FIELD_CHANGED',
  INQUIRY_STATUS_CHANGED = 'INQUIRY_STATUS_CHANGED',
  NEW_INQUIRY = 'NEW_INQUIRY',
}
