export enum InquiryDocumentType {
  INVOICE = 'INVOICE',
  QUOTATION = 'QUOTATION',
  PROFORMA_INVOICE = 'PROFORMA_INVOICE',
  DELIVERY_RECEIPT = 'DELIVERY_RECEIPT',
  SPECIFICATION = 'SPECIFICATION',
  OTHER = 'OTHER',
}
