export enum PartnerAdditionType {
  CUSTOMER = 'CUSTOMER',
  SHIPPER = 'SHIPPER',
  CONSIGNEE = 'CONSIGNEE',
  NOTIFY_PARTY = 'NOTIFY_PARTY',
  CARRIER = 'CARRIER',
  CO_LOADER = 'CO_LOADER',
  AIR_LINE = 'AIR_LINE',
  TRUCK_VENDOR = 'TRUCK_VENDOR',
  OTHER_VENDORS = 'OTHER_VENDORS',
}
